# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sangi Naveen Kumar
email: nkprince007@gmail.com
author: Sangi Naveen Kumar
secondary_email: nkprince007@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Sangi Naveen Kumar - Web Developer, Designer and Software Enthusiast. I love
  creating things with a new perspective. An ardent lover of "Keep it simple, silly." policy.
  CSE Undergraduate @ NIT Durgapur. Goes by the handle, nkprince007.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nkprince007.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nkprince007
github_username:  nkprince007
gitlab_username: nkprince007
spotify_username: nkprince007
instagram_username: naveenkumarsangi
facebook_username: naveen.007.prince
linkedin_username: nkprince007

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
port: 8000
sass:
  style: compressed
